### ISSUE TITLE
Lang File not working

### ISSUE THREAD

**Issue by danielslim** [amcharts/dataloader#17]
try every possible way i could think of to load Lang Translation since there's no examples shown how to use it but none are working.

**Comment by maertz** [comment]
Besides loading the language file into your enviroment, you need to set the language in your chart instance.
```

var chart = AmCharts.makeChart("chartdiv", {
  ...
  "language": "fr",
  "dataLoader": {
  ...
  }
});
```
https://codepen.io/team/amcharts/pen/2a7230f641df4b11a0f29d0cc6850e85
http://docs.amcharts.com/3/javascriptcharts/AmChart#language

**Comment by danielslim** [comment]
THk, it works.  When include the dataloader lang file, i get format error on console, i guess that's because chart lang instance not set. When i did set, nothing was changing which likely due to browser cache till i add version to force reload js file, or put the lang translation directly in html file which works as well.

**Comment by maertz** [comment]
Glad to hear it worked out for you. Regarding the issue, ensure to load the language file of the dataloader after the plugin itself otherwise it can't assign/add the new language to the plugin.
