### ISSUE TITLE
[New feature] onComplete

### ISSUE THREAD

**Issue by dmachehin** [amcharts/dataloader#3]
Need callback option: onComplete

**Comment by martynasma** [comment]
### Added in 1.0.1
- Added "complete", "load" and "error" properties that can be set with function handlers to be invoked on load completion, successful file load or failed load respectively

**Comment by markedmondson** [comment]
It'd be really useful to have the chart object available in these callbacks. Eg:

```
callFunction( options.complete, chart );
```

**Comment by martynasma** [comment]
Done. Thanks!
