### ISSUE TITLE
[enhancement] Need new external methods: setUrl(), reload()

### ISSUE THREAD

**Issue by dmachehin** [amcharts/dataloader#9]
Need function/method for change data url and (or) function for reload new data by url.
Maybe with new "url" param: chart.dataloader.reload/reloadUrl(url)

**Comment by martynasma** [comment]
You can do so already by changing `chart.dataLoader.url` and calling `chart.dataLoader.loadData()`, i.e.:

```
function loadNewData(url) {
  chart.dataLoader.url = url;
  chart.dataLoader.loadData()
}
```

**Comment by opcode0x** [comment]
@martynasma It's not working for Stock Chart,
I think it's a bad case to use:

``` js
chart.dataSets[0]..dataLoader.url = url;
chart.dataSets[1]..dataLoader.url = url;
```

or even in forEach loop

**Comment by martynasma** [comment]
Why it's a bad case?

**Comment by opcode0x** [comment]
@martynasma Sorry, I have no thoughts how to improve it.
